site_name: NameRate
site_url: https://docs.namerate.tech
docs_dir: '../../docs/en'

theme:
  custom_dir: '../../overrides/'
  name: material
  palette:
    - scheme: slate
      primary: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: orange
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  icon:
    admonition:
      failure: octicons/gear-16

  logo: assets/nmrt_logo_round_full_mini.png
  favicon: assets/favicon-16x16.png
  features:
    - header.autohide
    - navigation.instant
    - navigation.expand
    - navigation.footer
  language: en

extra:
  alternate:
      - name: English
        link: /en/
        lang: en
      - name: Русский
        link: /ru/
        lang: ru
  status:
    new: Will be added later
    deprecated: Deprecated

markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - md_in_html
  - attr_list
  - pymdownx.superfences
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - index.md
  - about.md
  - advantages.md
  - how-it-works.md
  - tokenomics.md
  - token-flow.md
  - speculation-prevention.md
  - roadmap.md
  - API.md
  - Presale-Whitelist.md
  - dictionary.md
  
